// Generated by GitHub Copilot
/**
 * Keyboard input state manager.
 * Tracks pressed keys and exposes helpers for 4-directional movement.
 */

const keys = {};
let jumpPressed = false;
let attackPressed = false;

/**
 * Initialise keyboard listeners on the document.
 * Call once at startup.
 */
export function initInput() {
  document.addEventListener('keydown', (e) => {
    keys[e.code] = true;
    if (e.code === 'Space') jumpPressed = true;
    if (e.code === 'KeyF')  attackPressed = true;
  });

  document.addEventListener('keyup', (e) => {
    keys[e.code] = false;
  });
}

/**
 * Returns the horizontal (X-axis) movement direction.
 * @returns {number} -1 (left), 0 (none), or 1 (right)
 */
export function getHorizontal() {
  const left = keys['ArrowLeft'] || keys['KeyA'] ? 1 : 0;
  const right = keys['ArrowRight'] || keys['KeyD'] ? 1 : 0;
  return right - left;
}

/**
 * Returns the vertical (Z-axis) movement direction.
 * @returns {number} -1 (forward/up), 0 (none), or 1 (backward/down)
 */
export function getVertical() {
  const up = keys['ArrowUp'] || keys['KeyW'] ? 1 : 0;
  const down = keys['ArrowDown'] || keys['KeyS'] ? 1 : 0;
  return down - up;
}

/**
 * Returns true once per jump press (consumed on read).
 * @returns {boolean}
 */
export function consumeJump() {
  if (jumpPressed) {
    jumpPressed = false;
    return true;
  }
  return false;
}

/**
 * Returns true once per attack press (F key), consumed on read.
 * @returns {boolean}
 */
export function consumeAttack() {
  if (attackPressed) {
    attackPressed = false;
    return true;
  }
  return false;
}
