// Generated by GitHub Copilot
/**
 * Physics module – wraps @dimforge/rapier3d-compat.
 * Provides world initialisation and body-creation helpers.
 */
import RAPIER from '@dimforge/rapier3d-compat';

/** @type {RAPIER.World} */
let world;

/**
 * Initialise the Rapier WASM runtime and create the physics world.
 * Must be awaited before any other physics calls.
 * @returns {Promise<RAPIER.World>}
 */
export async function initPhysics() {
  await RAPIER.init();
  world = new RAPIER.World({ x: 0.0, y: -9.81 * 2, z: 0.0 });
  return world;
}

/**
 * Returns the active Rapier world.
 * @returns {RAPIER.World}
 */
export function getWorld() {
  return world;
}

/**
 * Step the physics simulation by one fixed timestep.
 */
export function stepPhysics() {
  world.step();
}

/**
 * Create a static rigid body with a cuboid collider.
 * @param {{ x: number, y: number, z: number }} position – centre of the body
 * @param {{ hx: number, hy: number, hz: number }} halfExtents – half sizes
 * @returns {RAPIER.RigidBody}
 */
export function createStaticBody(position, halfExtents) {
  const bodyDesc = RAPIER.RigidBodyDesc.fixed()
    .setTranslation(position.x, position.y, position.z);
  const body = world.createRigidBody(bodyDesc);

  const colliderDesc = RAPIER.ColliderDesc.cuboid(
    halfExtents.hx, halfExtents.hy, halfExtents.hz
  ).setFriction(1.0);
  world.createCollider(colliderDesc, body);

  return body;
}

/**
 * Create a dynamic rigid body with a capsule collider for a character.
 * Rotation is locked on all axes; Z translation is locked to keep
 * the character on the side-view plane.
 * @param {{ x: number, y: number, z: number }} position
 * @param {number} halfHeight – half the height of the capsule cylinder
 * @param {number} radius – capsule radius
 * @returns {RAPIER.RigidBody}
 */
export function createCharacterBody(position, halfHeight, radius) {
  const bodyDesc = RAPIER.RigidBodyDesc.dynamic()
    .setTranslation(position.x, position.y, position.z)
    .lockRotations()
    .setLinearDamping(0.5);
  const body = world.createRigidBody(bodyDesc);

  const colliderDesc = RAPIER.ColliderDesc.capsule(halfHeight, radius)
    .setFriction(0.7)
    .setFrictionCombineRule(RAPIER.CoefficientCombineRule.Max);
  world.createCollider(colliderDesc, body);

  return body;
}

/**
 * Create a static rigid body with a cylinder collider (for tree trunks, etc.).
 * @param {{ x: number, y: number, z: number }} position – centre of the body
 * @param {number} halfHeight – half height of the cylinder
 * @param {number} radius – cylinder radius
 * @returns {RAPIER.RigidBody}
 */
export function createCylinderBody(position, halfHeight, radius) {
  const bodyDesc = RAPIER.RigidBodyDesc.fixed()
    .setTranslation(position.x, position.y, position.z);
  const body = world.createRigidBody(bodyDesc);

  const colliderDesc = RAPIER.ColliderDesc.cylinder(halfHeight, radius)
    .setFriction(0.5);
  world.createCollider(colliderDesc, body);

  return body;
}

/**
 * Create a dynamic rigid body with a capsule collider for a monster NPC.
 * Smaller than the player capsule; rotation locked.
 * @param {{ x: number, y: number, z: number }} position
 * @param {number} halfHeight – half the height of the capsule cylinder
 * @param {number} radius – capsule radius
 * @returns {RAPIER.RigidBody}
 */
export function createMonsterBody(position, halfHeight, radius) {
  const bodyDesc = RAPIER.RigidBodyDesc.dynamic()
    .setTranslation(position.x, position.y, position.z)
    .lockRotations()
    .setLinearDamping(0.3);
  const body = world.createRigidBody(bodyDesc);

  const colliderDesc = RAPIER.ColliderDesc.capsule(halfHeight, radius)
    .setFriction(0.7)
    .setFrictionCombineRule(RAPIER.CoefficientCombineRule.Max);
  world.createCollider(colliderDesc, body);

  return body;
}

/**
 * Remove a rigid body from the physics world (e.g. on monster death).
 * @param {import('@dimforge/rapier3d-compat').RigidBody} body
 */
export function removeBody(body) {
  world.removeRigidBody(body);
}

/**
 * Cast a short ray downward from a position to detect ground contact.
 * @param {RAPIER.RigidBody} body – the character body
 * @param {number} distance – max ray length (usually slightly more than capsule half-height + radius)
 * @returns {boolean} true if the ray hits a surface within distance
 */
export function isGrounded(body, distance) {
  const pos = body.translation();
  const ray = new RAPIER.Ray({ x: pos.x, y: pos.y, z: pos.z }, { x: 0, y: -1, z: 0 });
  const hit = world.castRay(ray, distance, true, undefined, undefined, undefined, body);
  return hit !== null;
}
